### ISSUE TITLE
Direct link to uploaded files

### ISSUE THREAD

**Issue by dimorinny** [Imgur/mandible#110]
Hi, I am trying to uploading and hosting images by your project using local driver. After uploading image I got something similar:
```
{
	"data": {
		"link": "/Users/jarvis/imagestore/original/6/U/6U5ohM5",
		"mime": "image/jpeg",
		"name": "maxresdefault.jpg",
		"hash": "6U5ohM5",
		"size": 180888,
		"width": 1920,
		"height": 1080,
		"ocrtext": "",
		"thumbs": {},
		"user_id": ""
	},
	"status": 200,
	"success": true
}
```
And after that is there a possible to download this image using direct link?
Thanks.

**Comment by andytuba** [comment]
Yes, the hash is used for the direct link URL.

    `https://i.imgur.com/%s.jpg` % hash
