### ISSUE TITLE
Make server.initServer method public

### ISSUE THREAD

**Issue by yinhm** [Imgur/mandible#47]
Change server.initServer method to server.InitServer so we have the option to embed ImgurGo in an application instead of a standalone service.

**Comment by briankassouf** [comment]
This is something we want to do. Along with this change I believe we need a callback where your application can access the data (location and meta-data of the image) that is returned from an upload. Does this sound helpful as well?

**Comment by yinhm** [comment]
I may only want to embed ImgurGo in an application to ease development, eg: setup server in testcase.

For production I'm not mind to deploy it separately.

**Comment by briankassouf** [comment]
@yinhm This is now available, note the function has been renamed to `server.Start()` now though.

you can use the main.go file as a reference (https://github.com/Imgur/mandible/blob/master/main.go)

**Comment by yinhm** [comment]
Great work, many thanks.
