### ISSUE TITLE
can't store images on s3

### ISSUE THREAD

**Issue by ricky-ticky** [Imgur/mandible#71]
makes mandible app in amazon beanstalk.
mandible stores images to /tmp besides  AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, S3_BUCKET are set.
How to debug it?

**Comment by Juriv** [comment]
any response on this?

**Comment by briankassouf** [comment]
@ricky-ticky is the s3 store setup in your config file? https://github.com/Imgur/mandible/blob/master/config/default.conf.json#L8

**Comment by briankassouf** [comment]
@ricky-ticky @Juriv closing for now, please check out the updated readme for directions on setting up s3 storage

**Comment by Juriv** [comment]
@berniesamson thanks, it works for us now
